version: '3.8'
services:
  backend:
    # МЫ ИСПОЛЬЗУЕМ ПЕРЕМЕННУЮ ${IMAGE_NAME} ЗДЕСЬ
    image: ghcr.io/${IMAGE_NAME}-backend:latest
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/teamdb
    ports:
      - "127.0.0.1:8081:8080"


  frontend:
    # И ЗДЕСЬ ТОЖЕ ПЕРЕМЕННАЯ
    image: ghcr.io/${IMAGE_NAME}-frontend:latest
    restart: always
    ports:
      - "127.0.0.1:3000:80"
