version: '3.8'
services:
  backend:
    # МЫ ИСПОЛЬЗУЕМ ПЕРЕМЕННУЮ ${IMAGE_NAME} ЗДЕСЬ
    image: ghcr.io/${IMAGE_NAME}-backend:latest
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/teamdb
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      # Убедитесь, что юзернейм совпадает с тем, что в БД (по умолчанию postgres)
      SPRING_DATASOURCE_USERNAME: postgres
    ports:
      - "127.0.0.1:8081:8080"
    depends_on:
      - db

  frontend:
    # И ЗДЕСЬ ТОЖЕ ПЕРЕМЕННАЯ
    image: ghcr.io/${IMAGE_NAME}-frontend:latest
    restart: always
    ports:
      - "127.0.0.1:3000:80"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: teamdb
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: